### ISSUE TITLE
About labels and training

### ISSUE THREAD

**Issue by barkntuncer** [supernotman/RetinaFace_Pytorch#25]
Hello, 
I am following your instructions to train the network. However, the label file, in the website, is not like how you described it in the instructions. I changed the name of the bounding box and annotations txt file name to label.txt and the dataloader.py code cannot read it. What is the solution to that problem ?
To be more clear the file in the website of the widerface is like that:

0--Parade/0_Parade_marchingband_1_849.jpg
1
449 330 122 149 0 0 0 0 0 0 
0--Parade/0_Parade_Parade_0_904.jpg
1
361 98 263 339 0 0 0 0 0 0 
0--Parade/0_Parade_marchingband_1_799.jpg
21
78 221 7 8 2 0 0 0 0 0 
78 238 14 17 2 0 0 0 0 0 
113 212 11 15 2 0 0 0 0 0 
134 260 15 15 2 0 0 0 0 0 
163 250 14 17 2 0 0 0 0 0 
201 218 10 12 2 0 0 0 0 0 
182 266 15 17 2 0 0 0 0 0 

And the output of the train.py is like that:

Traceback (most recent call last):
  File "train.py", line 150, in <module>
    main()
  File "train.py", line 53, in main
    dataset_train = TrainDataset(train_path,transform=transforms.Compose([Resizer(),PadToSquare()]))
  File "/home/barkntuncer/RetinaFace_Pytorch/dataloader.py", line 45, in __init__
    label = [float(x) for x in line]
  File "/home/barkntuncer/RetinaFace_Pytorch/dataloader.py", line 45, in <listcomp>
    label = [float(x) for x in line]
ValueError: could not convert string to float: '0--Parade/0_Parade_marchingband_1_849.jpg'

**Comment by kanzali** [comment]
Hello, 
I got the same problem too when I was working in windows, when I check the label.txt for training there is no float just images's names. So I change this file with the one here "Download annotations (face bounding boxes & five facial landmarks) " and it works and then I get an error on validation.
So I change to Ubuntu and it's working well.
Good luck

**Comment by barkntuncer** [comment]
Ahh thank you. I must have missed that part since my dropbox is full :D. I will check this on monday and probably close the issue.
Thanks
